CREATE DATABASE UserASP

USE UserASP


CREATE TABLE Users
(ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Login NVARCHAR(50) NOT NULL UNIQUE,
Password NVARCHAR(500) NOT NULL,
Email NVARCHAR(50) NOT NULL,
Pic VARBINARY(MAX) NOT NULL
)

DROP TABLE Users

SELECT * FROM Users

DELETE FROM Users WHERE id>0