CREATE DATABASE UserASP

USE UserASP


CREATE TABLE Users
(ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Login NVARCHAR(50) NOT NULL UNIQUE,
Password NVARCHAR(500) NOT NULL,
Email NVARCHAR(50) NOT NULL,
Pic VARBINARY(MAX) NOT NULL
)

DROP TABLE Users

SELECT * FROM Users

DELETE FROM Users WHERE id>0


CREATE TABLE Products
(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(50) NOT NULL,
Discription NVARCHAR(500) NOT NULL,
Price FLOAT NOT NULL,
Count BIGINT NOT NULL,
Pic VARBINARY(MAX) NOT NULL
)

drop table Products

SELECT * FROM Products