CREATE DATABASE UserASP

USE UserASP

DROP DATABASE UserASP


CREATE TABLE Users
(ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Login NVARCHAR(50) NOT NULL UNIQUE,
Password NVARCHAR(500) NOT NULL,
Email NVARCHAR(50) NOT NULL,
Pic VARBINARY(MAX) NOT NULL
)

DROP TABLE Users

SELECT * FROM Users

DELETE FROM Users WHERE id>0




CREATE TABLE Products
(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(50) NOT NULL UNIQUE,
Discription NVARCHAR(500) NOT NULL,
Price FLOAT NOT NULL,
Count BIGINT NOT NULL,
Pic VARBINARY(MAX) NOT NULL
)

drop table Products

SELECT * FROM Products




CREATE TABLE Cart
(	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(ID) ON DELETE CASCADE,
    ProductId INT NOT NULL REFERENCES Products(Id) ON DELETE CASCADE,
    Count BIGINT NOT NULL
)

drop table Cart

SELECT * FROM Cart


DELETE FROM Cart WHERE ID > 0